package com.aquatrax.tracklep.DataModels

data class MyProfile(
    val AccountNumber: Int,
    val AddressId: Int,
    val AlternateEmailID: Any,
    val CityName: String,
    val CommunicationAddress: String,
    val CommunicationAddress1: String,
    val CommunicationAddress2: Any,
    val CommunicationZipCode: String,
    val CustomerId: Int,
    val CustomerNo: String,
    val DefaultAccountNumber: Int,
    val DefaultAddressId: Int,
    val DefaultPayId: Any,
    val DefaultPayType: Any,
    val EmailId: String,
    val FullName: String,
    val HintsAns: String,
    val HintsAns2: String,
    val HomePhone: String,
    val IsPOBox: Any,
    val MobilePhone: String,
    val Parameters: Any,
    val Properties: String,
    val SecurityQuestion: String,
    val SecurityQuestion2: Any,
    val SecurityQuestionId: Int,
    val SecurityQuestionId2: Int,
    val SqlQuery: Any,
    val StateName: String,
    val UtilityAccountNumber: String
)